server:
  port: 7771

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/pms_user_db
    username:
    password:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    dispatch-options-request: true

  main:
    allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka